blank_issues_enabled: true
# contact_links:
#   - name: Questions & Discussions
#     url: https://github.com/cawa-93/vite-electron-builder/discussions/categories/q-a
#     about: Use GitHub discussions for message-board style questions and discussions.
